age = input("Enter your age : ")
age = int(age)
shamsiyear = input("Enter Shamsi Year :")
shamsiyear = int(shamsiyear)
miladiyear = input("Enter Miladi Year :")
miladiyear = int(miladiyear)
print("Your birth year is " )
print("Shamsi :" , shamsiyear-age)
print("Miladi :" , miladiyear-age)
print("Details :")
print("Months :" , age*12)
print("Weeks :" , age*52)
print("Days :" , age*365)
print("Hours :" , age*8760)
print("Minutes :" , age*525600)
print("Seconds :" , age*31536000)